---
stages:
  - lint
  - test
  - cleanup_docker
  - cleanup_ownership

before_script:
  # fix permissions if executing in docker
  - test $EUID -eq 0 || sudo -E chown -R $USER $HOME

flake8:
  stage: lint
  tags:
    - executor_docker
  image: python:3.6-slim
  script:
    - cat /etc/resolv.conf
    - whoami
    - pwd
    - pip -V
    - pip install -r requirements/local.txt
    - flake8

lint_dockerfile:
  stage: lint
  tags:
    - executor_docker
  allow_failure: true  # TODO remove after dockerfiles cleanups
  image: hadolint/hadolint:latest-debian
  script:
    - find * -type f -name "Dockerfile*" -print0 | xargs -0 -n1 hadolint

yamllint:
  stage: lint
  tags:
    - executor_docker
  image: python:3.6-slim
  script:
    - cat /etc/resolv.conf
    - whoami
    - pwd
    - pip -V
    - pip install yamllint
    - yamllint .

docker_compose:
  stage: test
  tags:
    - executor_shell
  before_script:
    - lockfile-create --verbose --retry 60 --lock-name /tmp/${CI_RUNNER_ID}.docker_compose.lock
    - ls -la /tmp/*.lock
    - sudo -E chown -R $USER $HOME
  script:
    - cat /etc/resolv.conf
    - whoami
    - pwd
    - docker --version
    - docker-compose --version
    - docker-compose build
    - docker-compose up -d
  script:
    - docker ps
    - docker-compose run django python manage.py migrate
    - docker-compose run django python manage.py test
    - docker-compose run django coverage run manage.py test luncher
    - docker-compose run django coverage report
    - docker-compose run django coverage html
    - docker-compose run django coverage xml
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'
  after_script:
    - docker-compose down --timeout 30
    - lockfile-remove --verbose --lock-name /tmp/${CI_RUNNER_ID}.docker_compose.lock
    - test $EUID -eq 0 || sudo -E chown -R $USER $HOME
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - htmlcov
      - coverage.xml
  dependencies: []
