# Generated by Django 2.0.10 on 2019-02-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.MealCategory'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
