# Generated by Django 2.0.10 on 2019-02-22 21:05

from django.db import migrations, models
import pendulum


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=pendulum.today),
        ),
    ]
