# Generated by Django 2.0.10 on 2019-07-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20190226_2151'),
        ('meals', '0004_auto_20190222_2105'),
    ]

    operations = [
    ]
